# Quarkus application configuration
quarkus.banner.enabled=false
quarkus.log.category."io.quarkus".level=OFF

# Packaging configuration
quarkus.package.jar.enabled=false
quarkus.package.jar.type=uber-jar
quarkus.package.output-name=fizzbuzz
quarkus.package.jar.add-runner-suffix=false
quarkus.native.enabled=true
