name: CI

on:
  push:
    branches:
      - main
    paths:
      - '**.java'
      - '**.gradle'
      - '**.kts'
      - 'gradle/**'
      - '.github/workflows/**'
      - '!**.md'
      - '!LICENSE'
      - '!.gitignore'
      - '!.gitattributes'
  workflow_dispatch:

jobs:
  gradlewTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "25"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Test with Gradle
        run: ./gradlew test

  gradlewNativeCompile:
    name: Build native image for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # In case of Linux, we use GraalVM as the JDK to run Gradle, and we use the Mandrel container to build the native image.
      # In case of macOS, we use GraalVM for both running Gradle and building the native image.
      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: "25"
          distribution: "graalvm-community"
          # If you want to build a native image with the --static and --libc=musl option on Linux in the future, you need to set this option to true and use the GraalVM directly on the GitHub Actions runner instead of using the Mandrel container.
          # Note that the fully static native executables support is experimental in Quarkus, for now.
          # https://quarkus.io/guides/building-native-image#build-fully-static-native-executables
          native-image-musl: false
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Compile Native Image
        run: ./gradlew build

      - name: Run Built Native Image
        run: ./build/fizzbuzz
